name       : evopop-gtk-theme
version    : 0.23
release    : 3
source     :
    - https://github.com/poltertec/evopop-gtk-theme/releases/download/0.23/evopop-gtk-theme-0.23.tar.xz : 7f5d6b458be80e5e3634172b674b836b6f912e07c1b230faf94728320122ded1
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Evolve OS & Budgie Desktop
description: |
    A simple, flat and bold Gtk theme for Evolve OS & Budgie Desktop. Iris Dark was used as base.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
