name       : viewnior
version    : 1.4
release    : 1
source     :
    - https://github.com/xsisqox/Viewnior/archive/viewnior-1.4.tar.gz : 44beaeaadf843ce2f63e339994f18ae6c524b23c967379441738ecff6c436b00
license    : GPL-3.0
summary    : Fast and elegant image viewer
clang      : no
description: |
    Viewnior, an image viewer program. Created to be simple, fast and elegant. It's minimalistic interface provides more screenspace for your images.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(exiv2)
    - pkgconfig(shared-mime-info)
    - gnome-common
setup      : |
    ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
