name       : vlc
version    : 2.2.0
release    : 2
source     :
    - http://get.videolan.org/vlc/2.2.0/vlc-2.2.0.tar.xz : 5e0a27e248c47da723a696420aca3a4dd15cc3ed8cc81618d3f1dc8661b25517
license    :
    - LGPL-2.1
    - GPL-2.0
summary    : Open source multimedia player
# Revisit when clang is fixed
clang      : no
description: |
    VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.
builddeps  :
    - pkgconfig(libidn)
    - pkgconfig(dbus-1)
    - pkgconfig(lua-5.1)
    - pkgconfig(vorbis)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(libmodplug)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libva-drm)
    - pkgconfig(vpx)
    - pkgconfig(speexdsp)
    - pkgconfig(x264)
    - pkgconfig(libass)
    - pkgconfig(egl)
    - pkgconfig(gl)
    - pkgconfig(xcb)
    - pkgconfig(xcb-shm)
    - pkgconfig(xcb-composite)
    - pkgconfig(xproto)
    - pkgconfig(xcb-xv)
    - pkgconfig(xcb-randr)
    - pkgconfig(vdpau)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(libpulse)
    - pkgconfig(alsa)
    - pkgconfig(Qt5Core)
    - pkgconfig(xpm)
    - pkgconfig(xinerama)
    - pkgconfig(xext)
    - pkgconfig(gnutls)
    - pkgconfig(taglib)
    - pkgconfig(libbluray)
    - pkgconfig(libaacs)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libnotify)
    - libmad-devel
    - liba52dec-devel
    - libgcrypt-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
