name        : sqlite3
version     : 3.8.8.3
release     : 5
source      :
    - http://www.sqlite.org/2015/sqlite-autoconf-3080803.tar.gz : 74576964cd9db44c13bf95d6a7c36b06cfdfb2fe4e3e26c9ce1ae0b2e328b411
homepage    : http://www.sqlite.org/
license     :
    - Public-Domain
summary     : Self contained SQL package
description : |
    The SQLite package is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
setup      : |
    %configure --disable-static \
            CFLAGS="$CFLAGS -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1     \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1       \
            -DSQLITE_SECURE_DELETE=1"
build      : |
    %make
install    : |
    %make_install
