name       : journal
version    : 1.0
release    : 2
source     :
    - https://github.com/evolve-os/journal/archive/v1.0.tar.gz : 14fe22c2a1fab5a54e2692c2c36811f70b7746f1a56c2d04884dfdd87ef0cf0a
license    : GPL-2.0
summary    : Journal text editor
description: |
     A lightweight text-editor with sharing and customizing options.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gtksourceview-3.0)
    - vala
setup      : |
    mkdir build
    cd build
build      : |
    %cmake
    %make
install    : |
    %make_install
