name       : caribou
version    : 0.4.17
release    : 1
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/caribou/0.4/caribou-0.4.17.tar.xz : 31828886b812421dd7217a7aa29043945b8601f3a101507f7e3faa0dc157e516
license    : LGPL
summary    : A text entry and UI navigation application (on-screen keyboard)
description: |
    A text entry and UI navigation application
builddeps  :
    - pkgconfig(pygobject-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(gdk-3.0)
    - pkgconfig(x11)
    - pkgconfig(gee-0.8)
    - pkgconfig(atspi-2)
    - pkgconfig(xtst)
    - libxklavier-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
